version: "3.8"

x-build-args: &build_args
    INSTALL_PYTHON_VERSION: "3.10.10"
    INSTALL_NODE_VERSION: "16.20.2"

x-default-volumes: &default_volumes
    volumes:
        - ./:/app
        - node-modules:/app/node_modules
        - ./dev.db:/tmp/dev.db

services:
    flask-dev:
        build:
            context: .
            target: development
            args:
                <<: *build_args
        image: "flask_boilerplate-development"
        ports:
            - "8080:5000"
            - "2992:2992"
        <<: *default_volumes
        links:
            - mysql
        depends_on:
            - mysql    


    manage:
        build:
            context: .
            target: development
            args:
                <<: *build_args
        entrypoint: flask
        environment:
            FLASK_ENV: production
            FLASK_DEBUG: 0
        image: "flask_boilerplate-manage"
        stdin_open: true 
        tty: true
        <<: *default_volumes
    
    mysql:
        image: mysql:8.4.0
        environment:
            MYSQL_ROOT_PASSWORD: test # for development only
            MYSQL_DATABASE: mydb
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: test 
        ports:
            - "9090:80"  
        depends_on:
            - mysql

volumes:
    node-modules:
    mysql-data:
