version: "3.8"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.10.10"
  INSTALL_NODE_VERSION: "20.9.0"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db

services:
  frontend:
    build:
      context: ./frontend
    image: "frontend"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules_fe:/app/node_modules

  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "backend-development"
    ports:
      - "8080:5000"
      - "2992:2992"
    environment:
        FLASK_APP: autoapp.py
        FLASK_ENV: development
    <<: *default_volumes
    links:
      - mysql
    depends_on:
      - mysql

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "backend-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

  mysql:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: test # for development only
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "9090:80"
    depends_on:
      - mysql

volumes:
  node_modules_fe:
  node-modules:
  mysql-data:
