"""empty message

Revision ID: 01494e26500d
Revises: 55361a39ed87
Create Date: 2024-04-26 02:23:10.934485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01494e26500d'
down_revision = '55361a39ed87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
