"""empty message

Revision ID: 0a89f35a48f4
Revises: 9c8bedb07956
Create Date: 2024-05-02 02:15:30.811543

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a89f35a48f4"
down_revision = "9c8bedb07956"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("infor", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(sa.Column("author_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "authors", ["author_id"], ["id"])
        batch_op.drop_column("author")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(sa.Column("author", sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("author_id")

    op.drop_table("authors")
    # ### end Alembic commands ###
