"""empty message

Revision ID: 97a83480fdff
Revises: 5d2d66f3f1c3
Create Date: 2024-05-29 17:14:46.573773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97a83480fdff'
down_revision = '5d2d66f3f1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('date', sa.String(length=255), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('book_table_ibfk_1', type_='foreignkey')
        batch_op.drop_column('genre')
        batch_op.drop_column('published_year')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('published_year', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('genre', mysql.VARCHAR(length=255), nullable=False))
        batch_op.create_foreign_key('book_table_ibfk_1', 'author_table', ['author_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('price')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
